// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MINIPROJECT.Migrations
{
    [DbContext(typeof(DataContextApp))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MINIPROJECT.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AP_REGNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APPTYPEID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRANCHID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIK_REFERENSI")
                     .IsRequired()
                     .HasColumnType("nvarchar(max)");

                    b.Property<string>("USERID")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACTIVE")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");


                    b.HasKey("Id");

                    b.ToTable("APP");
                });
#pragma warning restore 612, 618
        }
    }
}
