// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MINIPROJECT.Migrations
{
    [DbContext(typeof(DataContextCUSTDEBITUR))]
    partial class CUSTDEBITURContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MINIPROJECT.CUSTDEBITUR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AP_REGNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CU_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CU_CIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CU_DOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CU_POB")
                     .IsRequired()
                     .HasColumnType("nvarchar(max)");

                    b.Property<string>("CU_KTP_NO")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                    b.Property<string>("CU_HP")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                    b.Property<string>("CU_EMAIL")
                   .IsRequired()
                   .HasColumnType("nvarchar(max)");

                    b.Property<string>("CU_NPWP")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");


                    b.HasKey("Id");

                    b.ToTable("CUSTDEBITUR");
                });
#pragma warning restore 612, 618
        }
    }
}
