// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MINIPROJECT.Migrations
{
    [DbContext(typeof(DataContextScuser))]
    partial class SCUSERContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MINIPROJECT.Scuser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("USERID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GROUPID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SU_FULLNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SU_ACTIVE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                  
                    b.HasKey("Id");

                    b.ToTable("SCUSER");
                });
#pragma warning restore 612, 618
        }
    }
}
